# Generated by Django 4.2.24 on 2025-09-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_availability_user_experience_user_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
