# Generated by Django 4.2.24 on 2025-09-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='unknow', max_length=100),
        ),
    ]
